#!/usr/bin/with-contenv bash

# 启动定时任务,默认一小时执行一次
# 启动subfinder查找字幕
s6-setuidgid abc \
	subfinder /media \
	-c /config/subfinder.json
echo ==============本轮搜索已结束，下次遍历为${TASK}后==============
sleep $TASK
