#!/usr/bin/with-contenv bash

# 检查config配置文件，并创建
if [ ! -e "/config/subfinder.json" ] ;  then 
cp /subfinder/subfinder.json /config/subfinder.json
fi

# permissions
chown -R abc:abc \
    /config \
    /media


